// Google Sheets Configuration
// This file is generated by GitHub Actions during deployment
// For local development, copy config.example.js to config.js

const GOOGLE_SHEETS_CONFIG = {
    // These values will be replaced by GitHub Actions during deployment
    SHEET_ID: '__GOOGLE_SHEET_ID__',
    API_KEY: '__GOOGLE_API_KEY__',
    
    // Sheet name and range (adjust as needed)
    SHEET_NAME: 'General',
    RANGE: 'A:J',
    
    // Whether to use sample data instead of Google Sheets
    USE_SAMPLE_DATA: false
};

// Export configuration
if (typeof module !== 'undefined' && module.exports) {
    module.exports = GOOGLE_SHEETS_CONFIG;
} else {
    window.GOOGLE_SHEETS_CONFIG = GOOGLE_SHEETS_CONFIG;
}